[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
akashi = "72xay1vadtYKWM7BxSdXy7LQSCj3MRv8FsgFy4AmeSFz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mvkvc/.config/solana/id.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
