# fly.toml app configuration file generated for ctransfer-site on 2023-11-27T14:46:50-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ctransfer-site"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
