VERSION 0.7

ARG --global DATE=(date +%y-%m-%d)
ARG --global DEBIAN_VERSION=bullseye-slim
ARG --global NODE_MAJOR=18

image:
    FROM node:${NODE_MAJOR}-${DEBIAN_VERSION}
    WORKDIR /app

deps:
    FROM +image
    COPY . .
    RUN yarn install --dev

build:
    FROM +deps

docker:
    FROM +build
    ENV HOST=0.0.0.0
    ENV PORT=3000
    EXPOSE 3000
    CMD ["yarn", "serve"]
    SAVE IMAGE ctransfer-js:latest
    SAVE IMAGE --push registry.fly.io/ctransfer-js:latest registry.fly.io/ctransfer-js:${DATE}

deploy:
    RUN fly deploy --image registry.fly.io/ctransfer-js:latest
