VERSION 0.7

ARG --global DATE=(date +%y-%m-%d)
ARG --global DEBIAN_VERSION=slim-bullseye
ARG --global RUST_VERSION=1.74
ARG --global NODE_MAJOR=18

image:
    FROM rust:${RUST_VERSION}-${DEBIAN_VERSION}
    WORKDIR /app
    RUN apt-get update
    RUN apt-get install -y ca-certificates curl gnupg git build-essential
    RUN cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
    RUN avm install latest
    RUN avm use latest
    RUN mkdir -p /etc/apt/keyrings
    RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
    RUN apt-get update
    RUN apt-get install nodejs -y

deps:
    FROM +image
    COPY . .
    RUN npm i -D

test:
    FROM +deps
    RUN anchor test

build:
    FROM +deps
    RUN anchor build
    SAVE ARTIFACT target AS LOCAL target
