name: app_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - services/app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: earthly ./services/app+deploy
